<a href="https://colab.research.google.com/github/KhushiAgg/NewsSummarization/blob/main/TextSummarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing and Cleaning Dataset

In [ ]:
import numpy as np
import pandas as pd

import os

In [ ]:
summary = pd.read_csv('news_summary.csv', encoding='iso-8859-1')
raw = pd.read_csv('news_summary_more.csv', encoding='iso-8859-1')

In [ ]:
pre1 =  raw.iloc[:,0:2].copy()
# pre1['head + text'] = pre1['headlines'].str.cat(pre1['text'], sep =" ")

pre2 = summary.iloc[:,0:6].copy()
pre2['text'] = pre2['author'].str.cat(pre2['date'].str.cat(pre2['read_more'].str.cat(pre2['text'].str.cat(pre2['ctext'], sep = " "), sep =" "),sep= " "), sep = " ")

In [ ]:
pre = pd.DataFrame()
pre['text'] = pd.concat([pre1['text'], pre2['text']], ignore_index=True)
pre['summary'] = pd.concat([pre1['headlines'],pre2['headlines']],ignore_index = True)
pre.head(5)

text  \
0  Saurav Kant, an alumnus of upGrad and IIIT-B's...   
1  Kunal Shah's credit card bill payment platform...   
2  New Zealand defeated India by 8 wickets in the...   
3  With Aegon Life iTerm Insurance plan, customer...   
4  Speaking about the sexual harassment allegatio...   

                                             summary  
0  upGrad learner switches to career in ML & Al w...  
1  Delhi techie wins free food from Swiggy for on...  
2  New Zealand end Rohit Sharma-led India's 12-ma...  
3  Aegon life iTerm insurance plan helps customer...  
4  Have known Hirani for yrs, what if MeToo claim...

In [ ]:
pre.shape

(102915, 2)

Shape of the Dataset with NULL values *(102915, 2)*

In [ ]:
pre.text.describe()

count                                                102797
unique                                               102756
top       England was beaten at home for the first time ...
freq                                                      2
Name: text, dtype: object

In [ ]:
pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102915 entries, 0 to 102914
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   text     102797 non-null  object
 1   summary  102915 non-null  object
dtypes: object(2)
memory usage: 1.6+ MB


In [ ]:
len(str(pre['text'].values).split()) #65 sum # 1504 text # max_text_len=100 max_summary_len=15

1504

In [ ]:
pre['text'][0]

"Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

In [ ]:
pre['summary'][0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

In [ ]:
pre['text'][1]

"Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more."

In [ ]:
pre['summary'][1]

'Delhi techie wins free food from Swiggy for one year on CRED'

In [ ]:
print(pre.shape)
print(pre.isnull().sum())

(102915, 2)
text       118
summary      0
dtype: int64


In [ ]:
pre_clean = pre.dropna().drop_duplicates()
#pre_clean['summary'] = pre['summary'].dropna().drop_duplicates()

In [ ]:
print(pre_clean.shape)
print(pre_clean.isnull().sum())

(102775, 2)
text       0
summary    0
dtype: int64


Shape of the Dataset without NULL values *(102775, 2)*

In [ ]:
def clean_text(text, remove_stopwords = True):
    '''Remove unwanted characters, stopwords, and format the text to create fewer nulls word embeddings'''

    # Convert words to lower case
    #text = text.lower()

    # Replace contractions with their longer forms
    if True:
        text = text.split()
        new_text = []
        for word in text:
            if word in contraction_mapping:
                new_text.append(contraction_mapping[word])
            else:
                new_text.append(word)
        text = " ".join(new_text)
    return text

In [ ]:
 contraction_mapping ={"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not",

                           "didn't": "did not", "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not",

                           "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",

                           "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would",

                           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would",

                           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam",

                           "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have",

                           "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock",

                           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have",

                           "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is",

                           "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as",

                           "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would",

                           "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have",

                           "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have",

                           "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are",

                           "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",

                           "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is",

                           "where've": "where have", "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have",

                           "why's": "why is", "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have",

                           "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have", "y'all": "you all",

                           "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have",

                           "you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have",

                           "you're": "you are", "you've": "you have"}

In [ ]:
# Clean the summaries and texts
clean_summaries = []
for summary in pre_clean.summary:
    clean_summaries.append(clean_text(summary))
print("Summaries are complete.")

clean_texts = []
for text in pre_clean.text:
    clean_texts.append(clean_text(text))
print("Texts are complete.")

Summaries are complete.
Texts are complete.


In [ ]:
clean_summaries[0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

In [ ]:
clean_texts[0]

"Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

# Cleaned Dataset Samples

In [ ]:
for i in range(5):
    print("Clean Review #",i+1)
    print("Summary",clean_summaries[i])
    print("Texts",clean_texts[i])
    print()


Clean Review # 1
Summary upGrad learner switches to career in ML & Al with 90% salary hike
Texts Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers.

Clean Review # 2
Summary Delhi techie wins free food from Swiggy for one year on CRED
Texts Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more.

Clean Review # 3
Summary New Zealand end Rohit Sharma-led India's 12-match winning st

# Dividing into train and test samples

In [ ]:
idx = int(0.95*len(clean_texts))
print(len(clean_texts))
print(idx)
print(len(clean_texts)-idx)
train_texts = clean_texts[:idx]
test_texts = clean_texts[idx:]
train_sum = clean_summaries[:idx]
test_sum = clean_summaries[idx:]


102775
97636
5139


In [ ]:
train_df = pd.DataFrame({'summary' : train_sum,
                         'text' : train_texts},
                                columns=['summary','text'])


In [ ]:
train_df['summary'][0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

In [ ]:
test_df = pd.DataFrame({'summary' : test_sum,
                        'text' : test_texts},
                                columns=['summary','text'])

In [ ]:
test_df.head()

summary  \
0  'Chanakya of Odisha Politics' Mohapatra passes...   
1  German building demolished by 250 kg of explos...   
2  Romania and Italy unite to halt abuse of women...   
3  I carry four devices including an iPhone: Oppo...   
4  Rare genetic condition makes iris' muscles to ...   

                                                text  
0  Former Rajya Sabha MP and President of Odisha ...  
1  An 18-storey building complex in Germany was d...  
2  The Romanian government has agreed to collabor...  
3  Chinese smartphone brands Oppo and Vivo's Co-f...  
4  China-based doctors found a rare case of eye m...

# MODELS

In [ ]:
!pip install --upgrade tensorflow
!pip install --upgrade tensorflow-io

In [ ]:
!pip install -U transformers
!pip install -U torch

In [ ]:
import spacy
import re
import torch
import os
import json

from transformers import T5Tokenizer, T5ForConditionalGeneration, T5Config

In [ ]:
pip install sentencepiece

##Model: Summarization using T5 model
##Text-to-Text Transformer

In [ ]:
T5_PATH = 'Einmalumdiewelt/T5-Base_GNAD'
t5_model = T5ForConditionalGeneration.from_pretrained(T5_PATH, output_past=True)
t5_tokenizer = T5Tokenizer.from_pretrained(T5_PATH)
x = t5_tokenizer(clean_texts, truncation=True, max_length=500)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def t5_summarize(input_text, num_beams=4, num_words=80):
    input_text = ' '.join(input_text.split())
    input_tokenized = t5_tokenizer.encode(input_text, return_tensors="pt").to(device)
    summary_task = torch.tensor([[21603, 10]]).to(device)
    input_tokenized = torch.cat([summary_task, input_tokenized], dim=-1).to(device)

    # Move the model to the same device as input tensors
    t5_model.to(device)

    summary_ids = t5_model.generate(input_tokenized,
                                    num_beams=int(num_beams),
                                    no_repeat_ngram_size=3,
                                    length_penalty=2.0,
                                    min_length=30,
                                    max_length=int(num_words),
                                    early_stopping=True)

    output = [t5_tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False)
    for g in summary_ids]
    return output[0]

In [ ]:
%%time
for i in range(6):

        print('news articles ',i + 1, " : \n" )
        print(t5_summarize(clean_texts[i]))
        print('............................................................................\n\n\n\n')

news articles  1  : 

Tech Mahindra's Saurav Kant, a graduate of upGrad's Online Power Learning program, is now a Data Scientist with a 90% salary hike.
............................................................................




news articles  2  : 

A Delhi techie has won a chance to win free food from Swiggy for a year. Users who spend more than 2000 CRED coins on a credit card will get a free meal.
............................................................................




news articles  3  : 

In the fourth ODI of the series, New Zealand defeated India by 8 wickets to win their first match of the five-match series.
............................................................................




news articles  4  : 

Aegon Life iTerm Insurance plan provides life cover up to the age of 100 years. Customers can also save up to 146,800 on taxes.
............................................................................




news articles  5  : 

"What if it is not true, the 

In [ ]:
def summarize_text(text):
    # Generate summary using the T5 model
    summary = t5_summarize(text)

    # Show the generated summary
    print("\nSummary:")
    print(summary)

# Prompt the user for input and generate summary
user_input = input("Enter the text to summarize: ")
summarize_text(user_input)

Enter the text to summarize: Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. UpGrad's Online Power Learning has powered 3 lakh+

Summary:
UpGrad's PG Program in Machine Learning and Artificial Intelligence helped alumnus Saurav Kant to become a Data Scientist at Tech Mahindra with 90% salary hike.


##Model: Summarization using bart model (seq2seq)

In [ ]:
from transformers import BartTokenizer, BartForConditionalGeneration, BartConfig

In [ ]:
bart_PATH = 'facebook/bart-large-cnn'
bart_model = BartForConditionalGeneration.from_pretrained(bart_PATH, output_past=True)
bart_tokenizer = BartTokenizer.from_pretrained(bart_PATH)
x = bart_tokenizer(clean_texts, truncation=True, max_length=500)

In [ ]:
def bart_summarize(input_text, num_beams=4, num_words=80):
    #input_text = str(input_text)
    input_text = ' '.join(input_text.split())
    input_tokenized = bart_tokenizer.encode(input_text, return_tensors='pt')
    summary_ids = bart_model.generate(input_tokenized,
                                      num_beams=int(num_beams),
                                      no_repeat_ngram_size=3,
                                      length_penalty=2.0,
                                      min_length=80,
                                      max_length=int(num_words),
                                      early_stopping=True)
    output = [bart_tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids]
    return output[0]

In [ ]:
%%time
for i in range(6):

        print('news article ',i + 1, " : \n" )
        print(bart_summarize(clean_texts[i]))
        print('............................................................................\n\n\n\n')

news article  1  : 

Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. UpGrad's Online Power Learning has powered 3 lakh+
............................................................................




news article  2  : 

Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ix
............................................................................




news article  3  : 

New Zealand defeated India by 8 wickets in the fourth ODI at Hamilton on Thursday. India lost an international match under Rohit Sharma's captai

In [ ]:
def summarize_text(text):
    # Generate summary using the bart model
    summary = bart_summarize(text)

    # Show the generated summary
    print("\nSummary:")
    print(summary)

# Prompt the user for input and generate summary
user_input = input("Enter the text to summarize: ")
summarize_text(user_input)

Enter the text to summarize: Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. UpGrad's Online Power Learning has powered 3 lakh+

Summary:
Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. UpGrad's Online Power Learning has powered 3 lakh+


#Evaluation Metrics

## ROUGE SCORE

In [ ]:
!pip install rouge-score
!pip install rouge

  Preparing metadata (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=a4849432f624e11a2ee675c913c9769a2424b7cefab92dc07cbacc2ef35d0192
  Stored in directory: /root/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
Successfully built rouge-score


In [ ]:
from rouge import Rouge

# Define the generated summary and reference summary
generated_summary_T5 = '''UpGrad's PG Program in Machine Learning and Artificial Intelligence helped alumnus Saurav Kant to become a
Data Scientist at Tech Mahindra with 90% salary hike.'''
reference_summary = '''upGrad learner switches to career in ML & Al with 90% salary hike'''
# Initialize Rouge scorer
rouge_scorer = Rouge()

# Calculate ROUGE scores
rouge_scores = rouge_scorer.get_scores(generated_summary_T5,
                                       reference_summary)


print("ROUGE Scores:")
print(rouge_scores)

ROUGE Scores:
[{'rouge-1': {'r': 0.46153846153846156, 'p': 0.24, 'f': 0.3157894691828255}, 'rouge-2': {'r': 0.25, 'p': 0.125, 'f': 0.16666666222222234}, 'rouge-l': {'r': 0.38461538461538464, 'p': 0.2, 'f': 0.2631578902354571}}]


In [ ]:
from rouge import Rouge

# Define the generated summary and reference summary

generated_summary_bart = '''Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence,
was a Sr Systems Engineer at Infosys. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at
Tech Mahindra with 90% salary hike. UpGrad's Online Power Learning has powered 3 lakh+'''
reference_summary = '''upGrad learner switches to career in ML & Al with 90% salary hike'''
# Initialize Rouge scorer
rouge_scorer = Rouge()

# Calculate ROUGE scores
rouge_scores = rouge_scorer.get_scores(generated_summary_bart,
                                       reference_summary)

print("ROUGE Scores:")
print(rouge_scores)

ROUGE Scores:
[{'rouge-1': {'r': 0.6153846153846154, 'p': 0.16666666666666666, 'f': 0.262295078613276}, 'rouge-2': {'r': 0.25, 'p': 0.058823529411764705, 'f': 0.09523809215419511}, 'rouge-l': {'r': 0.5384615384615384, 'p': 0.14583333333333334, 'f': 0.22950819336737438}}]
